#!/usr/bin/env bash

names=(
"Sangeetha Udayadas"
"Praveen Bhaskarani"
"Voleti Sai Naga Pranav"
"Ayush Garg"
"Arjita Arora"
"Anju Mehta"
"Nisa S. S"
"Shailesh Patil"
"Ravindra Mishra"
"Manish Mishra"
"Aswanth Christy R"
"Srikrishnudu nagandla"
"Taraprakash Sahoo"
"Sougat Debnath"
"Yogeshkumar Patel"
"Ashish Katiyar"
"Poomagal C T"
"Manoj Kumar M K"
"Juan Gonzalez"
"Sebulon David"
"Akshan Kumar"
"Shelendra Gupta"
"Manasa"
"Sasikumar Meghanathan"
"Moncy Kurien"
"Manoranjan Mallik"
"Ganesan"
"Suresh Krishnan"
"Mishi Vidya Sinku"
"Maulik Thakkar"
"Maulik Thakkar"
"Mike Salim"
"Balavishnu R"
"Karthikeyan Subramaniam"
"Richard Mason"
"Arighna Dutta"
"Mrityunjay Singh"
"Shams Tabrez"
"Lohit Ambati"
"Syed Ghazanfar Hussain"
"Ayushi Aggarwal"
"Ashmika Agarwal"
"Ramesh Goud Peddoti"
"Lohitha Kadire"
"Sunny Vijay Rout"
"Nirav Shah"
"Amit Sharma"
"Aiborlang Pyngrope"
"Narra Shyam Sunder Reddy"
"Mohammed Nazeer Baig"
"Subodh Patni"
"Pavan Santh Bommadevara"
"Yogesh Ramesh"
"Pankaj Kumar Patra"
"Sunil"
"Chandra Sekhar Nayak"
"Lakshmanan Balasubramanian"
"Dhanasekaran Ramakrishnan"
"Nicoleta Enescu"
"Pavitar Singh Arneja"
"Srikanth Perumbuduri"
"Harendra Kumar"
"Madhura Nale"
"Rajani Karuturi"
"bhagyalakshmi dasamaneni"
"Vinay patel"
"Satish"
"Bharani Movva"
"Shravya Gogula"
"Aaditya Bilakanti"
"KEERTHI AMBALA"
"Sravya Pidugu"
"Chris Joseph"
"Ajinkya Pawar"
"Durga Prasad Chimmili"
"Pradeep Kumar Myakala"
"Sai Chandra Priyanka Kona"
"Muntaka Muhammad"
"Ramasubramanian Murugan"
"Srikanth Komma"
"manasa padavala"
"Ashish Lakhani"
"Theophilius Amuah"
"Abdul Rahim"
"Chandrakala Bandaru"
"Neeraj Verma"
"Dr Nitin G Zadpe"
"C Sarat Chandra"
"Karunaakaran"
"Hongjae Jeon"
"Suraj Paul"
"Raksha Modi"
"Priya Santani"
"kamal singh thakur"
"Amjath Mohammad"
"Xristopher Pennington"
)

for name in "${names[@]}"; do
  folder_name="${name// /_}"
  mkdir -p "$folder_name"
  touch "$folder_name/README.md"
done
